### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by mzimmerman** [bobiverse/docxplate#31]
Hi, a user created a template (docx file) and our application creates a dynamic struct (using reflect) that is essentially just a key/value map, so there's no depth/embedded types and it's all string types too, and using this library generated this stack trace.  I will look into this more, but am just logging the issue.

```
http: panic serving 10.0.22.31:55676: runtime error: slice bounds out of range [24:8]
goroutine 173420434 [running]:
 net/http.(*conn).serve.func1()
    /usr/local/go/src/net/http/server.go:1898 +0xbe
 panic({0xf27de0?, 0xc00cab7278?})
    /usr/local/go/src/runtime/panic.go:770 +0x132
 github.com/bobiverse/docxplate.(*Template).Params.(*Template).fixBrokenPlaceholders.func2.1(0xc0b952aa00)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/Template.go:544 +0x3ba
 github.com/bobiverse/docxplate.(*xmlNode).Walk(0xc0b952a780, 0xc001292fa0)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/xml.node.go:62 +0x48
 github.com/bobiverse/docxplate.(*xmlNode).Walk(0xc0b952a480, 0xc001292fa0)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/xml.node.go:66 +0x5e
 github.com/bobiverse/docxplate.(*Template).Params.(*Template).fixBrokenPlaceholders.func2(0xc0b952a480)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/Template.go:527 +0xb3
 github.com/bobiverse/docxplate.(*xmlNode).Walk(0xc0b0488480, 0xc0012930b8)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/xml.node.go:62 +0x48
 github.com/bobiverse/docxplate.(*xmlNode).Walk(0xc0b0488400, 0xc0012930b8)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/xml.node.go:66 +0x5e
 github.com/bobiverse/docxplate.(*Template).fixBrokenPlaceholders(...)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/Template.go:513
 github.com/bobiverse/docxplate.(*Template).Params(0xc66e0a5aa0, {0x0?, 0x0?})
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/Template.go:213 +0x2e5
 github.com/bobiverse/docxplate.(*Template).Plaintext(0xc66e0a5aa0)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/Template.go:681 +0x32
 github.com/bobiverse/docxplate.(*Template).Placeholders(0xc190316050?)
    .go/pkg/mod/github.com/bobiverse/docxplate@v1.2.5/Template.go:628 +0x13
core.HandleGobyGenerate({0x14a94f0, 0xc09cb70000}, 0xc00036e6c0)
```

**Comment by bobiverse** [comment]
if there is no sensitive information, can you give document example?

Also (depending on your OS) try to "Clear formatting" parts where you have placeholders. That hopefully should help to generate document while you waiting for bug fix :baby_chick:

**Comment by bobiverse** [comment]
Oh,great! I'm adding it to test cases

**Comment by bobiverse** [comment]
I did find problem and ..

.. ended up totally rewriting function which fix broken (same _row_ element) and merge them together.

See branch `issue31` (https://github.com/bobiverse/docxplate/tree/issue31)

I'll test little more this and then make new version of `docxplate`.
